# NumPy

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = a.reshape(3,3) 
# 3 is rows 3 is columns
# this will convert single dimensional array to two dimensional array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Two dimenstional array have 2 tuples

In [14]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
type(a)

numpy.ndarray

In [15]:
a.dtype

dtype('int32')

In [17]:
print(a.shape)

(9,)


In [18]:
print(a[1])

2


In [20]:
a[0]=3
print(a)

[3 2 3 4 5 6 7 8 9]


In [27]:
a2d = np.array([[1,2,3],[4,5,6]])

In [28]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print(a2d.shape)

(2, 3)


In [31]:
a2d[0,1]

2

In [32]:
b = np.array([1,2,3,4,5,6,7,8,9])

In [33]:
np.arange(2,8,3)

array([2, 5])

In [34]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ide = np.diag()

Standard Deviation = deviation from the Mean

# Refer Trainers notebook