# NumPy Dimensions

    ● Python is created by Guido Van Rossom
    ● Year first released: 1991
    

In [1]:
import numpy as np

In [2]:
a = [[[2,5],[3,4],[10,20]],
     [[1,2],[3,4],[5,6]]]

In [3]:
print(np.ndim(a))

3


In [4]:
print(np.shape(a))

(2, 3, 2)


In [5]:
np_array_2d = np.arange(1,37)
print(np_array_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [6]:
np_array_2d = np_array_2d.reshape(3,4,3)
print(np_array_2d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [7]:
print(np_array_2d.shape)

(3, 4, 3)
