##  genfromtxt

In [9]:
import numpy as np
from numpy import genfromtxt
from io import StringIO 


In [10]:
df = pd.read_csv('data.csv')

NameError: name 'pd' is not defined

In [ ]:
my_data = genfromtxt(fname="data.csv", names=True, missing_values={0:""}, filling_values={0:'999'})
my_data

In [11]:
data = u"N/A, 2, 3\n4, ,???"
kwargs = dict(delimiter=",", dtype=int,names="a,b,c",missing_values={0:"N/A", 'b':" ", 2:"???"},
              filling_values={0:0, 'b':0, 2:-999})
np.genfromtxt(StringIO(data), **kwargs)

array([(0, 2,    3), (4, 0, -999)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<i4')])

## Logspace

In [12]:
np.logspace(start=3,stop=9.0, num=5, base=3, dtype=float)

array([   27.        ,   140.29611541,   729.        ,  3787.99511615,
       19683.        ])

## Slice function

In [13]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
s = slice(0,5,3)
print(s)

slice(0, 5, 3)


In [15]:
print(a[s])

[0 3]


In [16]:
type(s)

slice

In [17]:
arr1 = [True, False, False]
arr1=np.array(arr1)
print(arr1)

[ True False False]


In [18]:
arr2 = ~arr1
print(arr2)

[False  True  True]


In [19]:
a = np.arange(0,30,5)
print(a)

[ 0  5 10 15 20 25]


In [20]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25


In [21]:
for x in np.nditer(a, order='C'):
    print(x)

0
5
10
15
20
25


In [22]:
for x in np.nditer(a, order='F'):
    print(x)

0
5
10
15
20
25


### flat and flatten

In [6]:
import numpy as np

In [37]:
a = np.arange(6).reshape(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [38]:
a.shape

(3, 2)

In [9]:
print(np.rollaxis(a))

TypeError: rollaxis() missing 1 required positional argument: 'axis'

In [10]:
a = np.ones((3,4,5,6))
print(a)

[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1

In [5]:
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [6]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6)

In [7]:
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4)

## changing dimension using new axis 

In [43]:
a = np.array([3,4,5])
print(a.ndim)

1


In [47]:
b = a[:,np.newaxis] #row wise
print(b)

[[3]
 [4]
 [5]]


In [46]:
print(b.ndim)

2


In [48]:
b = a[np.newaxis,:] #row wise
print(b)

[[3 4 5]]


## changing dimension using

In [54]:
x = np.arange(36).reshape(2,3,2,3)

In [51]:
print(x.shape)

(2, 3, 2, 3)


In [53]:
print(x)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]]


## Squeeze

In [67]:
x = np.arange(9).reshape(3,3)

In [68]:
print(x.ndim)

2


In [69]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
y = np.squeeze(x)

In [71]:
print(y.ndim)

2


In [72]:
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [88]:
for i in range(9):
    print(i, bin(i))

0 0b0
1 0b1
2 0b10
3 0b11
4 0b100
5 0b101
6 0b110
7 0b111
8 0b1000


## numpy.char

In [89]:
firstName = ['Alex', 'Sugi', 'Niralya']
lastName = ['Palanisamy', 'Chellapandi', 'Alex']

In [90]:
fullName = np.char.add(firstName, lastName)

In [91]:
print(fullName)

['AlexPalanisamy' 'SugiChellapandi' 'NiralyaAlex']


In [95]:
name = "Debbie"
print(np.char.multiply(name, 3))

DebbieDebbieDebbie


In [96]:
print(np.char.multiply(firstName, 3))

['AlexAlexAlex' 'SugiSugiSugi' 'NiralyaNiralyaNiralya']


In [98]:
print(np.char.multiply(('a','b','c'), 3)) #can give list, tuple

['aaa' 'bbb' 'ccc']


In [100]:
print(np.char.multiply({'a','b','c'}, 3)) #not for set

TypeError: string operation on non-string array

In [103]:
b = np.char.center("Data Science", 30, '.') #for string

In [102]:
print(b)

.........Data Science.........


In [109]:
x = np.char.center(fullName, 100, '*') # for each element in NumPy array
print(x)

['*******************************************AlexPalanisamy*******************************************'
 '******************************************SugiChellapandi*******************************************'
 '********************************************NiralyaAlex*********************************************']


In [121]:
x = np.char.join('-', fullName)

In [122]:
print(x)

['A-l-e-x-P-a-l-a-n-i-s-a-m-y' 'S-u-g-i-C-h-e-l-l-a-p-a-n-d-i'
 'N-i-r-a-l-y-a-A-l-e-x']


In [5]:
s = 'Alex'
b = '~'.join(s)
print(b)

A~l~e~x


In [34]:
a = np.char.encode('Data Science', 'hz')
print(a)

b'Data Science'


In [35]:
b = np.char.decode(a,'cp500')
print(b)

à/È/€ëÄÑÁ>ÄÁ


In [ ]:
# np.sin np.cos np.tan

In [36]:
a = np.array([1.0, 5.55, 0.567, 25.532])
print(a)

[ 1.     5.55   0.567 25.532]


In [40]:
b = np.around(a, decimals=1)
print(b)

[ 1.   5.6  0.6 25.5]


In [42]:
a = np.array([99,999,5,1.4])
b = np.around(a, decimals=-1)
print(b)

[ 100. 1000.    0.    0.]


In [44]:
a = np.array([0.25,1.33,1,100, 2])
print(a)

[  0.25   1.33   1.   100.     2.  ]


In [46]:
b = np.reciprocal(a) #reciprocal means 1 by something
print(b)

[4.        0.7518797 1.        0.01      0.5      ]


In [50]:
a = np.array([1,2,3,4,5]) #as it is integer the values also given as int
print(np.reciprocal(a))

[1 0 0 0 0]


In [49]:
a = np.array([1,2,3,4,5], dtype=float) #now this will consider as float
print(np.reciprocal(a))

[1.         0.5        0.33333333 0.25       0.2       ]


In [54]:
a = np.array([1,2,3,4,5]) 
print(np.power(a, 2))

[ 1  4  9 16 25]


In [56]:
b = np.array([2,3,2,3,2])
print(np.power(a,b)) #can give two arrays

[ 1  8  9 64 25]
