In [1]:
import numpy as np

In [2]:
a = np.array([1,3,5,7])
type(a)

numpy.ndarray

In [4]:
np.__version__()

TypeError: 'str' object is not callable

In [5]:
a = np.arange(0, 10, 2,  dtype ='float')
print(a)

[0. 2. 4. 6. 8.]


In [6]:
a = np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [7]:
arr = np.arange(15).reshape(3,5)

In [8]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
arr[0:2,:] #Implied start and end

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
arr[2,1:] #Implied end

array([11, 12, 13, 14])

In [11]:
arr[:2,2:4] #Implied zero

array([[2, 3],
       [7, 8]])

In [12]:
arr[:,::2] #Optional stride

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [13]:
arr[::1,::3]

array([[ 0,  3],
       [ 5,  8],
       [10, 13]])

In [14]:
arr.strides

(20, 4)

## Array views

In [16]:
a = np.arange(10)

In [18]:
b = a[3:7]
b

array([3, 4, 5, 6])

In [20]:
b[:] = 0

In [21]:
a

array([0, 1, 2, 0, 0, 0, 0, 7, 8, 9])

In [22]:
b.flags.owndata

False

In [23]:
a.flags.owndata

True

## sum

In [25]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
a.sum(axis = None) #or a.sum() #Reduces into single scalar

105

In [36]:
a.shape

(3, 5)

In [34]:
a.sum(axis = 0) #Reduces into the zeroth dimension

array([15, 18, 21, 24, 27])

In [35]:
a.sum(axis = 1) #Reduces into the first dimension

array([10, 35, 60])

# Broadcasting