In [315]:
import numpy as np

In [316]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [317]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [318]:
arr = arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [319]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [320]:
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [321]:
arr = arr * 3 + 5

In [322]:
arr

array([[ 5,  8, 11, 14, 17],
       [20, 23, 26, 29, 32]])

In [323]:
arr.dtype

dtype('int32')

In [324]:
arr.dtype.byteorder

'='

In [325]:
arr.dtype.itemsize

4

In [326]:
arr.dtype.name

'int32'

In [327]:
arr.dtype.type

numpy.int32

In [328]:
arr = np.array([1,2,3],dtype=np.int64)

In [329]:
arr

array([1, 2, 3], dtype=int64)

In [330]:
arr.dtype

dtype('int64')

In [331]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [332]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [333]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [334]:
np.ones((3,3)) #One initialized

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [335]:
np.empty((3,5)) #Un-initialized

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [336]:
np.eye(3) #idential matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [337]:
np.diag([7,4,2]) #Diagonal matrix

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 2]])

# Indexing and Slicing

In [338]:
# Ref PPT for visualization of below operations

In [339]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [340]:
arr = arr.reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [341]:
arr[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [342]:
arr[2,1:]

array([11, 12, 13, 14])

In [343]:
arr[:2,2:4]

array([[2, 3],
       [7, 8]])

In [344]:
arr[:,::2] #Optional Strides

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [345]:
arr[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [346]:
arr[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [347]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [348]:
b = a[3:7]
b

array([3, 4, 5, 6])

In [349]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [350]:
b[:] = 0

In [351]:
a

array([0, 1, 2, 0, 0, 0, 0, 7, 8, 9])

In [352]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [353]:
b = np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [354]:
c = a + b
c

array([10, 21, 32, 43, 54])

# Axis

In [355]:
a = np.arange(15)
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [356]:
a.sum() #default axis=None

105

In [357]:
a.sum(axis=0)

array([15, 18, 21, 24, 27])

In [358]:
a.sum(axis=1)

array([10, 35, 60])

# Broadcasting

In [359]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [360]:
c = a + 10
c

array([10, 11, 12, 13, 14])

In [361]:
a = np.arange(6)
a = a.reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [362]:
b = np.array([10,20,30])
b = b.reshape(3,1)
b

array([[10],
       [20],
       [30]])

In [363]:
c = a + b
c

array([[10, 11],
       [22, 23],
       [34, 35]])

In [364]:
# Square peg in round hole
# if dimensions do not match up, np.newaxis may be useful

In [365]:
a = np.arange(6).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [366]:
b = np.array([10,100])
b

array([ 10, 100])

In [368]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [369]:
b[:, np.newaxis].shape

(2, 1)

In [370]:
a * b[:, np.newaxis]

array([[  0,  10,  20],
       [300, 400, 500]])

In [371]:
# Array methods

In [372]:
a.any()

True

In [373]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [374]:
a.mean()

2.5

In [375]:
# Fancy Indexing

In [376]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [377]:
i = np.array([[0,1],[1,2]])
i

array([[0, 1],
       [1, 2]])

In [378]:
j = np.array([[2,1],[4,4]])
j

array([[2, 1],
       [4, 4]])

In [379]:
a[i,j]

array([[ 2,  6],
       [ 9, 14]])

In [380]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [381]:
b = (a % 3 == 0)
b

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [382]:
a[b]

array([ 0,  3,  6,  9, 12])