In [ ]:
N = int(input())
if (N%2) != 0:
    print("Weird")
else:
    if (N >= 2) & (N <= 5):
        print("Not Weird")
    elif (N >= 6) & (N <= 20):
        print("Weird")
    elif (N > 20):
        print("Not Weird")

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

In [4]:
# ABCDCDC

def total_occurances(string,sub):
    count = 0
    strLen = len(string)
    subLen = len(sub)
    if sub in string:
        start = 0
        end = subLen
        for i in string:
            if (sub in string[start:end]):
                count += 1
            start += 1
            end += 1
            if end > strLen:
                break
            
    return count
    
if __name__ == '__main__':
    string = input()
    sub = input()
    print(total_occurances(string, sub))

ALEXPRABUALEXALEX
ALE
STR NOW:  ALE
Start:  1
End:  4
STR NOW:  LEX
Start:  2
End:  5
STR NOW:  EXP
Start:  3
End:  6
STR NOW:  XPR
Start:  4
End:  7
STR NOW:  PRA
Start:  5
End:  8
STR NOW:  RAB
Start:  6
End:  9
STR NOW:  ABU
Start:  7
End:  10
STR NOW:  BUA
Start:  8
End:  11
STR NOW:  UAL
Start:  9
End:  12
STR NOW:  ALE
Start:  10
End:  13
STR NOW:  LEX
Start:  11
End:  14
STR NOW:  EXA
Start:  12
End:  15
STR NOW:  XAL
Start:  13
End:  16
STR NOW:  ALE
Start:  14
End:  17
STR NOW:  LEX
Start:  15
End:  18
3


In [11]:
def average(array):
    trees_with_distinct_heights = set(array)
    sum_of_distinct_heights = 0
    for i in trees_with_distinct_heights:
        sum_of_distinct_heights  += i
    avg = sum_of_distinct_heights/len(trees_with_distinct_heights)
    return avg

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


In [15]:
import textwrap

def wrap(string, max_width):
    wrappedTxt = ""
    strLen = len(string)

    start = 0
    end = max_width
    for i in string:
        wrappedTxt = wrappedTxt + string[start:end] + "\n"
        start += max_width
        end += max_width
            
    return wrappedTxt

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)
    
# ABCDEFGHIJKLIMNOQRSTUVWXYZ

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ






















In [19]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())    
    t = tuple(integer_list)
    print(hash(t))

2
1 2
3713081631934410656


In [1]:
a = int(input())
b = int(input())
c = int(input())
d = int(input())

result = (a**b) + (c**d)
print(result)


9
29
7
27
4710194409608608369201743232


In [2]:
sample_dict = {1:"Alex", 2: "Kitty", 3:"Debbie", 4:"Niralya"}

In [3]:
sample_dict

{1: 'Alex', 2: 'Kitty', 3: 'Debbie', 4: 'Niralya'}

In [4]:
sample_dict[5] = 'Hello'

In [5]:
sample_dict

{1: 'Alex', 2: 'Kitty', 3: 'Debbie', 4: 'Niralya', 5: 'Hello'}

In [6]:
sample_dict[3]

'Debbie'

In [7]:
sample_dict[3] = 'Deb'

In [8]:
sample_dict

{1: 'Alex', 2: 'Kitty', 3: 'Deb', 4: 'Niralya', 5: 'Hello'}

In [10]:
a = "123"
type(a)

str

In [14]:
a = int(a)
a

123

In [15]:
type(a)

int

In [16]:
a = 'alex'
a = int(a)

ValueError: invalid literal for int() with base 10: 'alex'

In [17]:
lst = [1,3,5,4,3,4]
tup = tuple(lst)
tup

(1, 3, 5, 4, 3, 4)

In [18]:
sett = set(lst)

In [19]:
sett

{1, 3, 4, 5}

In [20]:
sett2 = set(tup)

In [21]:
sett2

{1, 3, 4, 5}

In [24]:
list_of_lists = [[1,2],["a","b"],["hello",["hi","hai"]]]

In [25]:
list_of_lists

[[1, 2], ['a', 'b'], ['hello', ['hi', 'hai']]]

In [26]:
dict_from_list_of_lists = dict(list_of_lists)

In [27]:
dict_from_list_of_lists

{1: 2, 'a': 'b', 'hello': ['hi', 'hai']}

In [30]:
a = int(input("enter a number: "))
a

enter a number: 33


33

In [32]:
lst = list(input("Enter number: "))
lst

Enter number: 123456789


['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
modulo = lambda x,y: x%y

In [5]:
modulo(9,3)

0

In [8]:
square = lambda x: x**2

In [9]:
square(3)

9

In [ ]:
# Write a function to square the each values in list and return as list (using Lambda)

In [15]:
square = lambda x:x**2
lst = [3,2,4,1,5]

def squareTheList(lst):
    lst1 = []
    for i in lst:
       lst1.append(square(i))
    return lst1

squareTheList(lst)

[9, 4, 16, 1, 25]

In [18]:
resultList = map(square, lst)
resultList
list(resultList)

[9, 4, 16, 1, 25]

In [19]:
resultList = map(lambda x:x**2, lst)
resultList
list(resultList)

[9, 4, 16, 1, 25]

In [23]:
def squareIt(a):
    return a**2

resultList = list(map(squareIt, lst))

resultList

[9, 4, 16, 1, 25]

In [24]:
# Write a program to filter vowels from the given list using filter function

In [25]:
listD = ['a','l','e','x']
vowel = ['a','e','i','o','u']

lst = list(filter(lambda x:x in vowel, listD))

In [26]:
lst

['a', 'e']

In [29]:
from functools import reduce

In [34]:
def functA(a,b):
    return a+b

lst=[1,2]
print(reduce(functA, lst))

3


In [ ]:
# Get a number from the user and find the factorial using lambda and reduce functions

In [47]:
num = int(input("Enter the number to find factorial: "))

fact = reduce(lambda x,y:x*y, range(1, num+1))
print(fact)

Enter the number to find factorial: 1
1


In [55]:
lst = [9,44,2,1,0,5,3,8,6]
greatest = reduce(lambda x,y: x if x>y else y, lst)
greatest

44

In [56]:
lst = [1,2,3,4,5]
lstNew = []
for i in lst:
    lstNew.append(i**2)
lstNew
    

[1, 4, 9, 16, 25]

In [57]:
[i**2 for i in lst]

[1, 4, 9, 16, 25]

In [61]:
[i for i in lst if i%2==0]

[2, 4]

In [65]:
['even' if i%2==0 else 'odd' for i in lst]

['odd', 'even', 'odd', 'even', 'odd']

In [66]:
a = 1
b = 0
a/b

ZeroDivisionError: division by zero

In [69]:
try:
    a = 1
    b = 0
    a/b
except:
    print("Divide by zero")

Divide by zero


In [75]:
try:
    a = int(input("enter the number: "))
except (ValueError) as v:
    print(v)
    print("pls enter a valid number")
except (Exception) as e:
    print(e)
finally:
    print("Good bye")

enter the number: hello 
invalid literal for int() with base 10: 'hello '
pls enter a valid number
Good bye


In [77]:
lst1 = [1,2,3,6,4]
lst2 = [5,3,7,6,1]

[i for i in lst1 for j in lst2 if i==j]

[1, 3, 6]

In [88]:
setX = {"Alex", "Sugi"}
{i for i in setX}

{'Alex', 'Sugi'}

In [4]:
class test:
    abc = "Alex"
    def __init__(self, x):
        self.abc = x
        

In [7]:
obj1 = test()
obj1.abc

TypeError: __init__() missing 1 required positional argument: 'x'

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b*10+4

array([[14, 24, 34],
       [44, 54, 64],
       [74, 84, 94]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.dtype

dtype('int32')

In [30]:
arr = np.array([1,2,3],dtype=np.float32)

In [31]:
arr

array([1., 2., 3.], dtype=float32)

In [32]:
type(arr)

numpy.ndarray

In [33]:
arr.dtype

dtype('float32')

In [35]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
d = np.diag([1,5,9,8])
d

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 8]])

In [48]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
a[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
a[:,0]

array([0, 3, 6])

In [64]:
a[1:2,:]

array([[3, 4, 5]])

In [65]:
a[0:,1]

array([1, 4, 7])

In [66]:
a = np.arange(16)

In [67]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
a =  a.reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
a[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [70]:
a[::3,::3]

array([[ 0,  3],
       [12, 15]])

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a.sum()

120

In [73]:
a.sum(axis=0)

array([24, 28, 32, 36])

In [76]:
a.sum(axis=1)

array([ 6, 22, 38, 54])