In [ ]:
import numpy

def arrays(arr):
    arr = list(map(float,arr))
    revArr = []
    for i in range(len(arr)-1,-1,-1):
        revArr.append(arr[i])
    return numpy.array(revArr)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

# Best method - one liner

In [ ]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

In [3]:
import numpy as np
print("Enter values of N, M and P: ")
n, m, p  = map(int, input().strip().split(' '))

print("Enter values for array 1: ")
lst1 = []
for i in range(0,n):
    rowList = list(map(int, input().strip().split(' ')))
    lst1.append(rowList)
    
print("Enter values for array 2: ")
lst2 = []
for i in range(0,m):
    rowList = list(map(int, input().strip().split(' ')))
    lst2.append(rowList)
    
arr1 = np.array(lst1)
arr2 = np.array(lst2)
arr3 = np.concatenate((arr1, arr2), axis = 0)

print(arr3)

Enter values of N, M and P: 
4 3 2
Enter values for array 1: 
1 2
1 2
1 2
1 2
Enter values for array 2: 
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [37]:
import numpy
inputMap = tuple(map(int, input().strip().split(' ')))
print(numpy.zeros(inputMap, dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [38]:
print(numpy.ones(inputMap, dtype=numpy.int))

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [49]:
import numpy as np
n, m = map(int, input().strip().split(" "))
valuesA = []
for i in range(n):
     valuesA.append(list(map(int, input().strip().split(" "))))

valuesB = []
for i in range(n):
     valuesB.append(list(map(int, input().strip().split(" "))))

a = np.array(valuesA, dtype = np.int)
b = np.array(valuesB, dtype = np.int)

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
