In [2]:
abc = 1,000,000
abc

(1, 0, 0)

In [3]:
a b c = 1000 2000 3000

SyntaxError: invalid syntax (<ipython-input-3-fd5f99168ec0>, line 1)

In [7]:
a,b,c = 1000, 2000, 3000
c

3000

In [9]:
a_b_c = 1,000,000
a_b_c

(1, 0, 0)

In [10]:
{1,2,3,4}

{1, 2, 3, 4}

In [12]:
set((1,2,3,4))

{1, 2, 3, 4}

In [13]:
set([1,2,3,4])

{1, 2, 3, 4}

In [14]:
set([[1,2],[3,4]])

TypeError: unhashable type: 'list'

In [1]:
import pandas as pd


In [3]:
df = pd.read_csv(r"Automobile_Data.csv")

In [5]:
df.head(3)

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0

In [19]:
df.shape

(61, 10)

In [27]:
df[['company','price']]

company    price
0     alfa-romero  13495.0
1     alfa-romero  16500.0
2     alfa-romero  16500.0
3            audi  13950.0
4            audi  17450.0
5            audi  15250.0
6            audi  18920.0
7             bmw  16430.0
8             bmw  16925.0
9             bmw  20970.0
10            bmw  30760.0
11            bmw  41315.0
12            bmw  36880.0
13      chevrolet   5151.0
14      chevrolet   6295.0
15      chevrolet   6575.0
16          dodge   6377.0
17          dodge   6229.0
18          honda   7295.0
19          honda  12945.0
20          honda  10345.0
21          isuzu   6785.0
22          isuzu      NaN
23          isuzu      NaN
24         jaguar  32250.0
25         jaguar  35550.0
26         jaguar  36000.0
27          mazda   5195.0
28          mazda   6095.0
29          mazda   6795.0
..            ...      ...
31          mazda  18344.0
32  mercedes-benz  25552.0
33  mercedes-benz  28248.0
34  mercedes-benz  40960.0
35  mercedes-benz  45400.0
36     mitsubishi   5389.0
37     mitsubishi   6189.0
38     mitsubishi   6989.0
39     mitsubishi   8189.0
40         nissan   7099.0
41         nissan   6649.0
42         nissan   6849.0
43         nissan   7349.0
44         nissan  13499.0
45        porsche  34028.0
46        porsche  37028.0
47        porsche      NaN
48         toyota   5348.0
49         toyota   6338.0
50         toyota   6488.0
51         toyota   6918.0
52         toyota   7898.0
53         toyota   8778.0
54         toyota  15750.0
55     volkswagen   7775.0
56     volkswagen   7975.0
57     volkswagen   7995.0
58     volkswagen   9995.0
59          volvo  12940.0
60          volvo  13415.0

[61 rows x 2 columns]

In [28]:
import numpy as np

In [33]:
arr = np.array([2,3,5,6,9])
arr

array([2, 3, 5, 6, 9])

In [34]:
np.shape(arr)

(5,)

In [37]:
a = np.arange(10)
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
lst1 = [1,2,2]; lst2 = [3,33,3,99]; 

In [39]:
list(zip(lst1, lst2))

[(1, 3), (2, 33), (2, 3)]

In [46]:
earr = np.empty([1,3])
earr

array([[1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
mat = np.diag([1,2,3,4])
mat

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [50]:
mat[0:2, :]

array([[1, 0, 0, 0],
       [0, 2, 0, 0]])

In [52]:
mat[2,1:]

array([0, 3, 0])

In [53]:
mat

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
mat[:,::2]

array([[1, 0],
       [0, 0],
       [0, 3],
       [0, 0]])

In [60]:
v = np.arange(10,50,1)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [69]:
try:
    if '1' != 1:raise

SyntaxError: unexpected EOF while parsing (<ipython-input-69-e981c27e4a3d>, line 2)

In [76]:
x = ['ab', 'cd']
print(len(list(map(list, x))))

2


In [80]:
print('*', "abcde".center(6), '*', sep='')

*abcde *
